###
@host = http://localhost:8083
@imagename = mdeploy

@systemToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwiaWF0IjoxNTE2MjM5MDIyLCJzY29wZSI6InJlYWQ6aW1hZ2VzIGNyZWF0ZTpjb250YWluZXIgY3JlYXRlOmltYWdlIHJlYWQ6Y29udGFpbmVycyJ9.6_AFOIZ8EX82ChTI0NccqbtrvNm9P1H0ZJHy-eoEggY
####
GET {{host}}/mcm/v1/images
Authorization: bearer {{edgeToken}}

####
POST {{host}}/mcm/v1/images
Content-Type: multipart/form-data; boundary=$Boundary$
Authorization: Bearer {{edgeToken}}

--$Boundary$
Content-Disposition: form-data; name="image"; filename="{{imagename}}-v1.tar"

< ../deploy/{{imagename}}-v1.tar
--$Boundary$--


####
POST {{host}}/mcm/v1/containers
Content-Type: application/json
Authorization: Bearer {{edgeToken}}

{
  "env": {
    "MCM.BASE_API_PATH": "/{{imagename}}/v1",
    "MCM.WEBSOCKET_SUPPORT": "true",
    "OAUTH_GENERIC_KEY": "--oauth-system-generic-public-key--",
    "OAUTH_CLIENT_ID": "--oauth-client-id--",
    "OAUTH_CLIENT_SECRET": "--oauth-client-secret--",
    "SESSION_SECURITY_AUTHORIZATION_SET": "off",
    "MST_URL": "http://localhost:8025/mST/v1",
    "CUSTOMER_CODE": "--customer-code--",
    "MDEPLOYMENYAGENT_URL": "ws://",
    "SESSION_KEYS_MAP": "[{\"sessionId\": \"--random-16-chars--\",\"sessionSecret\": \"--random-32-chars--\",\"projectId\": \"--project-client-id--\"}]"
  },
  "id": "{{imagename}}-v1",
  "image": "{{imagename}}-v1",
  "imageId": "{{imagename}}-v1",
  "name": "{{imagename}}-v1",
  "state": "started"
}

###
GET {{host}}/{{clientId}}/{{imagename}}/v1/images
Content-Type: application/json
Authorization: Bearer {{edgeToken}}


####
GET {{host}}/{{clientId}}/{{imagename}}/v1/images
Content-Type: application/json
Authorization: Bearer {{systemToken}}


####
PUT {{host}}/{{clientId}}/{{imagename}}/v1/clients
Content-Type: application/json
Authorization: Bearer {{edgeToken}}

{
  "status": "active"
}

####
POST {{host}}/{{clientId}}/{{imagename}}/v1/images
Content-Type: application/json
Authorization: Bearer {{edgeToken}}

{
    "nodeId": "1d80503a96a893bec5a0dba50612b7dde2e438dd98793256bdd50a8f",
    "imageId": "4945ee3a-c655-404b-bde7-84727646d710-mreport-v1"
}

###
POST {{host}}/{{clientId}}/{{imagename}}/v1/images
Content-Type: application/json
Authorization: Bearer {{systemToken}}

{
    "nodeId": "1d80503a96a893bec5a0dba50612b7dde2e438dd98793256bdd50a8f",
    "imageId": "4945ee3a-c655-404b-bde7-84727646d710-mreport-v1"
}


####
POST {{host}}/{{clientId}}/{{imagename}}/v1/containers
Content-Type: application/json
Authorization: Bearer {{systemToken}}

{
  "env": {
    "AUTHORIZATION_KEY": "test",
    "MCM.BASE_API_PATH": "/mmodelshare/v1",
    "MCM.WEBSOCKET_SUPPORT": "false",
    "MODEL_URL": "http://url",
    "MODEL_VERSION": "1.0.0",
    "MAX_EVENT_COUNT": "5"
  },
  "id": "mmodelshare-v1",
  "imageName": "mmodelshare-v1",
  "imageId": "mmodelshare-v1",
  "name": "mmodelshare-v1",
  "state": "started"
}

###
POST http://localhost:8083/jsonrpc/v1
Content-Content-Type: application/json

{"jsonrpc": "2.0", "method": "getMe", "params": ["{{edgeToken}}"], "id": 1}
